from tutorial_db import Session, TutorialPageContent

session = Session()
session.query(TutorialPageContent).delete()

content_entries = [
    TutorialPageContent(title="INTRODUCTION",
                        content="\nCross-Site Scripting (XSS) is a vulnerability found in web applications that poses a significant threat to user security. In simple terms, it allows attackers to inject malicious scripts into web pages viewed by other users. Now, you might wonder, why is this a big deal? Well, let me explain.\n\nImagine you're browsing your favorite website, maybe a social media platform or an online store. You come across a seemingly harmless link, click on it, and suddenly, your account gets hijacked, or your personal information gets stolen. That's the danger of XSS. It can lead to serious consequences like data theft, session hijacking, website defacement, and even the distribution of malware.\n\nTo understand XSS better, let's break it down a bit. When you visit a website, your browser loads various elements like text, images, and scripts to display the page properly. Now, if an attacker manages to sneak their malicious script into one of these elements, it gets executed in your browser without you even knowing. This gives the attacker the ability to do things like stealing your login credentials, impersonating you, or even taking control of your account.\n\nNow, you might be wondering, how does this happen? Well, there are different types of XSS attacks, but they all essentially work by tricking the website into unknowingly executing the attacker's code. For example, an attacker might craft a malicious link and send it to you via email or social media. When you click on that link, the malicious script gets executed in your browser, giving the attacker access to your information.\n\nSo, why should you care about XSS? Because it's everywhere! Many popular websites and applications are vulnerable to XSS, which means anyone using those platforms could be at risk. That's why it's crucial to understand what XSS is and how to protect yourself against it.\n\nIn this tutorial, we'll cover everything you need to know about XSS, from how it works to how to prevent it. By the end, you'll have the knowledge and tools to keep yourself safe while browsing the web. So, let's dive in and learn more about this important topic!"),

    TutorialPageContent(title="UNDERSTANDING", 
                        content="\nCross-Site Scripting (XSS) occurs when an attacker successfully injects malicious scripts into web applications. These injected scripts are then executed in the browsers of unsuspecting users, leading to potential security breaches and attacks.\nTo understand XSS better, it's essential to know about its three main types:\n\n1. Reflected XSS: \nIn this type of attack, the injected script is reflected off a web server and then executed in the user's browser. This often happens when user input isn't properly sanitized or validated by the server before being included in the web page's response. When a user interacts with a vulnerable input field, such as a search box or URL parameter, the injected script gets executed, potentially compromising their session or stealing sensitive data.\n\n2. Stored XSS: \nAlso known as persistent XSS, this type of attack occurs when the injected script is stored on the server and then executed whenever a user accesses the affected page. Unlike reflected XSS, where the payload is part of the request and response cycle, stored XSS payloads are saved on the server, allowing them to affect multiple users over time. Attackers often exploit vulnerabilities in user-generated content features, such as comment sections or message boards, to plant malicious scripts that execute when other users view the content.\n\n3. DOM-based XSS: \nUnlike reflected and stored XSS, which rely on server-side processing, DOM-based XSS attacks occur entirely on the client side. In these attacks, the payload is injected into the Document Object Model (DOM) of the web page and then executed in the victim's browser. This type of XSS often involves manipulating client-side scripts, such as JavaScript, to modify the DOM and execute malicious code. DOM-based XSS vulnerabilities are challenging to detect and mitigate, as they don't involve server interactions and are specific to the client's browser environment."),

    TutorialPageContent(title="Common apps/websites vulnerable to XSS", 
                        content="\n1. Web Forums: Many online forums are vulerable to XSs, allowing attackers to execute scripts in the context of other users.\n\n2. Blogging Platforms: Context management systems like WordPress or Blogger may have XSS vulnerabilities, especially in user-generated content.\n\n3. E-commerce Websites: Online shopping sites often have XSS vulnerabilites in search fields, product reviews, or user comments sections.\n\n4. Webmail Service: Email services may be susceptible to XSS attacks, enabling attackers to steal session tokens or personal information."),

    TutorialPageContent(title="EXPLOITATION", 
                        content="\nIdentifying Vulnerabilities: Look for input fields, URLs and parameters that are not properly sanitized or validated\n\nCrafting Paylods: Craft malicious payloads using JavaScript to steal cookies, redirect users, deface pages, or perform malicious actions.\n\nInjection: Inject the payload into vulnerable input fields or URLs.\n\nTriggering: Once injected, the payload is triggere when another user accesses the affected page or performs certain actions"),

    TutorialPageContent(title="XSS Exploitation Tools", 
                        content="\nXSS Exploitation Tools refers to software or applications designed to identify, exploit, or defend against Cross-Site Scripting (XSS) vulnerabilities on websites and web applications. There are various tools available. They often provide features such as vulnerability scanning, payload injection, and real-time monitoring to help users detect and prevent XSS attacks effectively. Let us take a look at a few of these tools on the coming chapters."),

    TutorialPageContent(title="XSSer", 
                        content="""\nXsser is an tool for locating and taking advantage of XSS vulnerabilities in web applications. It is a useful tool for penetration testers because it offers a number of capabilities that automate the process of identifying and taking advantage of XSS vulnerabilities.\n\nINSTALLATION:\n    `git clone https://github.com/epsylon/xsser.git`\n    `cd xsser`\n    `./setup.py install`\n\nUSAGE:\n    Launch Xsser: `xsser`\n    For help: `xsser -h`\n    Perform a basic XSS scan on a target URL: `xsser -u <target_url>`\n    Specify a custom User-Agent: `xsser -u <target_url> --user-agent <custom_user_agent>`\n    User a proxy for HTTP requests: `xsser -u <target_url> --proxy http://<proxy_address>:<port>`\n\nEXAMPLE SCENARIO:\n    Suppose we have a web application hosted at "http://example.com/login"\n    Conduct Basic Scan: `xsser -u http://example.com/login`\n    Analyze results: Xsser will analyze the target URL for potential XSS vulnerabilities and display any discovered vulnerabilities\n    Exploit the vulnerabilty: Once a vulnerability is identified, Xsser provides options to exploit it\n    Xsser payload injection: Xsser will inject a payload into the vulnerable parameter and execute it in the context of the target application, demonstrating the exploitation of the XSS vulnerability\n
    """),
    
    TutorialPageContent(title="BeEF-XSS", 
                        content="""\nBeEF-XSS is a tool used for identifying and exploiting vulnerabilities in web browsers. It allows penetration testers to assess the security posture of web applications by targeting client-side vulnerabilities.     \nINSTALLATION:\n    `sudo apt update`\n    `sudo apt install beef-xss`\n\nUSAGE:\n    Start BeEF-XSS: `beef-xss`\n    Access BeEF-XSS: Open a web browser and navigate to `http://localhost:3000/ui/panel`\n    Create user account: Ensure that BeEF-XSS is properly configure and accessible through the web interface. After acecssing the web interface for the first time, you will be prompted to create a new user account. Follow the instructions to set up your account credetials.\n    Configure Hook: BeEF-XSS utilizes a JavaScript hook to establish communication with the target web browsers. Generate and copy the hook script provided by BeEF-XSS.\n    Inject Hook: Inject the hook script into the target web application or webpage. This can be done by adding the script tag with the hook code into the HTML code of the target page.\n\nEXAMPLE SCENARIO:\n    Suppose we have a web application hostead at "http://example.com/login"\n    Generate the hook script in the BeEF-XSS web interface and inject it into the login page of the target application\n    Once the hook script is injected, BeEF-XSS will establish a connection with any user who visits the compromised page\n    Exploit Browser: Below mentioned are some capabilities that BeEF-XSS allows the attacker:\n      * Execute commands in the victim's browser\n      * Capture the browser screenshots\n      * Redirect browser to malicious websites\n      * Gather information about the victim's system and browser\n    Monitor the BeEF-XSS dashboard for information gathered from the exploited browsers and analyze the data to understand the extent of the vulnerabilities and potential impact.
    """),

    TutorialPageContent(title="PwnXSS", 
                        content="""\nPwnXSS is a versatile tool designed for testing and exploiting Cross-Site Scripting (XSS) vulnerabilities in web applications. It provides an intuitive interface and powerful features for identifying, exploiting, and demonstrating the impact of XSS vulnerabilities.     \nINSTALLATION:\n    `git clone https://github.com/pwn0sec/PwnXSS.git`\n    `cd PwnXSS`\n    `chmod +x setup.sh`\n    `./setup.sh`\n\nUSAGE:\n    Start PwnXSS: `python3 pwnxss.py`\n    Access PwnXSS web interface: Open a web browser and navigate to `http://localhost:5000`\n    Configure settings:\n      * Set up proxy settings if required\n      * Customize other settings as per your preferences\n\nEXAMPLE SCENARIO:\n    Suppose we have a web application hostead at "http://example.com/login"\n    Set up the proxy settings in your web browser to route traffic through PwnXSS\n    Exploit XSS:\n      * Navigate to the login page of the target application\n      * Enter a malicious script in the input fields susceptible to XSS\n      * Submit the form to trigger the XSS vulnerability\n    Capture Data: PwnXSS will intercept the malicious script and capture data, including cookies, session tokens, and user credentials.                    
    """),

    TutorialPageContent(title="Preventive Measures", 
                        content="\nInput Validation: Validate and saitize all user inputs to prevent malicious scripts from being executed.\n\nOutput Encoding: Encode output data to prevent browsers from interpreting it as executable code.\n\nContent Security Policy (CSP): Implement CSP Headers to restrict the sources from which certain types of content can be loaded.\n\nRegular Security Audits: Regularly audit your web applications for vulnerabilites and promptly patch any identified issues.\n\nEducate Users: Train users to be cautious of suspicious links, and encourage the use of moder, secure browsers with built-in XSS protection."),
]

for entry in content_entries:
    session.add(entry)

session.commit()

session.close()
